/**
 * Startup Iceland Jobs Board - Jobs Data
 * Version: 1.0.0
 * Last Updated: 2026-01-19
 */

var StartupIcelandJobsData = {

    metadata: {
        lastUpdated: "2026-01-20",
        version: "1.0.0",
        totalJobs: 71
    },

    categories: {
        engineering: "Engineering",
        design: "Design",
        marketing: "Marketing",
        sales: "Sales",
        operations: "Operations",
        product: "Product",
        finance: "Finance",
        other: "Other"
    },

    types: {
        "full-time": "Full-time",
        "part-time": "Part-time",
        "contract": "Contract",
        "internship": "Internship"
    },

    levels: {
        entry: "Entry Level",
        mid: "Mid Level",
        senior: "Senior",
        lead: "Lead",
        executive: "Executive"
    },

    remoteOptions: {
        onsite: "Onsite",
        hybrid: "Hybrid",
        remote: "Remote"
    },

    jobs: [
        {
            id: 1,
            company: "Treble Technologies",
            companyLogo: null,
            title: "US General Manager",
            description: "Lead growth and strategic positioning in the US market, working with major customers and partners in tech and audio industries. Focus on commercial strategy, go-to-market positioning, and market-driven product input.",
            category: "sales",
            type: "full-time",
            experienceLevel: "executive",
            location: "United States",
            remote: "remote",
            salary: null,
            postedDate: "2026-01-19",
            applicationUrl: "https://treble.bamboohr.com/careers/34",
            featured: true
        },
        {
            id: 2,
            company: "Treble Technologies",
            companyLogo: null,
            title: "VP of Sales",
            description: "Direct global sales strategy and revenue growth. Build and lead a sales organization while handling complex enterprise deals. Position Treble's platform as the leading audio AI data generation solution.",
            category: "sales",
            type: "full-time",
            experienceLevel: "executive",
            location: "Reykjavik",
            remote: "hybrid",
            salary: null,
            postedDate: "2026-01-19",
            applicationUrl: "https://treble.bamboohr.com/careers/35",
            featured: true
        },
        {
            id: 3,
            company: "Treble Technologies",
            companyLogo: null,
            title: "Senior Audio AI Scientist",
            description: "Work at the intersection of audio ML, signal processing, and acoustic simulation. Collaborate with ML and research teams on training and evaluating audio AI systems using synthetic acoustics data.",
            category: "engineering",
            type: "full-time",
            experienceLevel: "senior",
            location: "Reykjavik",
            remote: "hybrid",
            salary: null,
            postedDate: "2026-01-19",
            applicationUrl: "https://treble.bamboohr.com/careers/31",
            featured: false
        },
        {
            id: 4,
            company: "Treble Technologies",
            companyLogo: null,
            title: "Technical Solutions Engineer",
            description: "Support sales and customer adoption through technical evaluation and proof-of-concept work. Demonstrate how Treble's capabilities improve audio AI systems while providing feedback to product and R&D teams.",
            category: "engineering",
            type: "full-time",
            experienceLevel: "mid",
            location: "Reykjavik",
            remote: "hybrid",
            salary: null,
            postedDate: "2026-01-19",
            applicationUrl: "https://treble.bamboohr.com/careers/33",
            featured: false
        },
        {
            id: 5,
            company: "Treble Technologies",
            companyLogo: null,
            title: "Application Engineer",
            description: "Span method development, benchmarking, quality assurance, technical content creation, and customer training on acoustic simulation and spatial audio applications.",
            category: "engineering",
            type: "full-time",
            experienceLevel: "mid",
            location: "Reykjavik",
            remote: "hybrid",
            salary: null,
            postedDate: "2026-01-19",
            applicationUrl: "https://treble.bamboohr.com/careers/30",
            featured: false
        },
        {
            id: 6,
            company: "Treble Technologies",
            companyLogo: null,
            title: "Scientific Software Engineer",
            description: "Develop and maintain the acoustics simulation engine, post-processing pipelines, and SDK integrations. Build production-grade software combining physics and numerical methods.",
            category: "engineering",
            type: "full-time",
            experienceLevel: "senior",
            location: "Reykjavik",
            remote: "hybrid",
            salary: null,
            postedDate: "2026-01-19",
            applicationUrl: "https://treble.bamboohr.com/careers/36",
            featured: false
        },
        {
            id: 7,
            company: "CCP Games",
            companyLogo: null,
            title: "Game Design Director",
            description: "Work with the Creative Director and EVE development teams to strengthen the design discipline, vision and process. Lead, mentor and build a diverse group of designers across multiple teams towards a shared game vision for EVE Online.",
            category: "design",
            type: "full-time",
            experienceLevel: "lead",
            location: "Reykjavik",
            remote: "hybrid",
            salary: null,
            postedDate: "2026-01-19",
            applicationUrl: "https://careers.ccpgames.com/en/postings/38bbae43-3698-49e1-9777-4de698f04965",
            featured: true
        },
        {
            id: 8,
            company: "CCP Games",
            companyLogo: null,
            title: "Narrative Designer",
            description: "Join the EVE Frontier team to shape the world of New Eden and its continuing narrative. Work with writers, artists, and other designers to develop narratively driven content for this hardcore Survival MMO set within the EVE Universe.",
            category: "design",
            type: "full-time",
            experienceLevel: "senior",
            location: "Reykjavik",
            remote: "hybrid",
            salary: null,
            postedDate: "2026-01-19",
            applicationUrl: "https://careers.ccpgames.com/postings/3918fe38-f52f-4e65-9890-f30f2bd2a4d3",
            featured: false
        },
        {
            id: 9,
            company: "Monerium",
            companyLogo: null,
            title: "Growth & Community Manager",
            description: "Expand reach and strengthen Web3 presence. Manage social platforms (Twitter, LinkedIn, Discord), develop marketing initiatives for user acquisition, build community relationships, and represent the company at industry conferences.",
            category: "marketing",
            type: "full-time",
            experienceLevel: "mid",
            location: "Remote (EU/EEA/UK)",
            remote: "remote",
            salary: null,
            postedDate: "2026-01-19",
            applicationUrl: "https://monerium.com/jobs/",
            featured: false
        },
        {
            id: 10,
            company: "Dohop",
            companyLogo: null,
            title: "Head of Partnerships – Middle East & India",
            description: "Grow and manage Dohop's airline partnerships across the Middle East and India. Identify growth opportunities, execute high-value deals, and collaborate with internal teams to drive expansion in the region.",
            category: "sales",
            type: "full-time",
            experienceLevel: "lead",
            location: "Remote",
            remote: "remote",
            salary: null,
            postedDate: "2026-01-19",
            applicationUrl: "https://dohop.bamboohr.com/careers",
            featured: false
        },
        {
            id: 11,
            company: "Dohop",
            companyLogo: null,
            title: "Partnerships Lead – APAC",
            description: "Drive Dohop's airline partnerships growth in the Asia-Pacific region. Develop strategic partnerships, execute high-value deals, and collaborate with product teams to expand Dohop's virtual interlining technology.",
            category: "sales",
            type: "full-time",
            experienceLevel: "lead",
            location: "Singapore",
            remote: "hybrid",
            salary: null,
            postedDate: "2026-01-19",
            applicationUrl: "https://dohop.bamboohr.com/careers",
            featured: false
        },
        {
            id: 12,
            company: "DTE",
            companyLogo: null,
            title: "Sales Manager – Europe",
            description: "Drive sales growth for DTE's industrial analytics solutions across European markets. Build relationships with metal industry clients and expand DTE's presence in the region.",
            category: "sales",
            type: "full-time",
            experienceLevel: "lead",
            location: "Remote (Italy, Spain or Germany)",
            remote: "remote",
            salary: null,
            postedDate: "2026-01-19",
            applicationUrl: "https://dteehf.bamboohr.com/careers",
            featured: false
        },
        {
            id: 13,
            company: "Climeworks",
            companyLogo: null,
            title: "Operations Engineer – Process",
            description: "Maintain safe and compliant plant operations at the Orca and Mammoth direct air capture plants. Work on daily operations and optimization projects for climate-positive technology.",
            category: "engineering",
            type: "full-time",
            experienceLevel: "mid",
            location: "Hellisheiði, Iceland",
            remote: "onsite",
            salary: null,
            postedDate: "2026-01-19",
            applicationUrl: "https://climeworks.com/careers-search",
            featured: false
        },
        {
            id: 14,
            company: "Climeworks",
            companyLogo: null,
            title: "Senior Maintenance Manager",
            description: "Lead maintenance operations at Climeworks' direct air capture plants in Iceland. Plan and execute maintenance activities for the Orca and Mammoth facilities.",
            category: "operations",
            type: "full-time",
            experienceLevel: "senior",
            location: "Hellisheiði, Iceland",
            remote: "onsite",
            salary: null,
            postedDate: "2026-01-19",
            applicationUrl: "https://climeworks.com/careers-search",
            featured: false
        },
        {
            id: 15,
            company: "Climeworks",
            companyLogo: null,
            title: "Production Surveillance Manager",
            description: "Oversee production monitoring and surveillance for Climeworks' direct air capture operations. Split role between Zurich headquarters and Iceland plant facilities.",
            category: "operations",
            type: "full-time",
            experienceLevel: "senior",
            location: "Zurich / Hellisheiði, Iceland",
            remote: "hybrid",
            salary: null,
            postedDate: "2026-01-19",
            applicationUrl: "https://climeworks.com/careers-search",
            featured: false
        },
        {
            id: 16,
            company: "Hopp",
            companyLogo: null,
            title: "Senior Full Stack Developer",
            description: "Create mobile apps, admin tools, and backend solutions for Iceland's leading micromobility company. Work with JavaScript, Node.js, React, GraphQL, and React Native.",
            category: "engineering",
            type: "full-time",
            experienceLevel: "senior",
            location: "Reykjavik",
            remote: "hybrid",
            salary: null,
            postedDate: "2026-01-20",
            applicationUrl: "https://www.tvinna.is/jobs/senior-full-stack-developer-3/",
            featured: false
        },
        {
            id: 17,
            company: "Kerecis",
            companyLogo: null,
            title: "Regenerative Surgical Specialist – Broward County",
            description: "Drive sales of Kerecis fish-skin regenerative tissue products to surgical customers in the Broward County, Florida region.",
            category: "sales",
            type: "full-time",
            experienceLevel: "mid",
            location: "Fort Lauderdale, FL, USA",
            remote: "onsite",
            salary: null,
            postedDate: "2026-01-16",
            applicationUrl: "https://careers.coloplast.com/Kerecis/go/Kerecis/9696001",
            featured: false
        },
        {
            id: 18,
            company: "Kerecis",
            companyLogo: null,
            title: "Key Accounts Director – Florida East",
            description: "Lead key account strategy and relationships for Kerecis regenerative tissue products across Eastern Florida.",
            category: "sales",
            type: "full-time",
            experienceLevel: "lead",
            location: "Miami, FL, USA",
            remote: "onsite",
            salary: null,
            postedDate: "2026-01-16",
            applicationUrl: "https://careers.coloplast.com/Kerecis/go/Kerecis/9696001",
            featured: false
        },
        {
            id: 19,
            company: "Kerecis",
            companyLogo: null,
            title: "Regenerative Surgical Specialist – Space Coast",
            description: "Drive sales of Kerecis fish-skin regenerative tissue products to surgical customers in the Space Coast, Florida region.",
            category: "sales",
            type: "full-time",
            experienceLevel: "mid",
            location: "Space Coast, FL, USA",
            remote: "onsite",
            salary: null,
            postedDate: "2026-01-16",
            applicationUrl: "https://careers.coloplast.com/Kerecis/go/Kerecis/9696001",
            featured: false
        },
        {
            id: 20,
            company: "Kerecis",
            companyLogo: null,
            title: "Project Support Intern",
            description: "Support supply chain and logistics projects at Kerecis operations facility.",
            category: "operations",
            type: "internship",
            experienceLevel: "entry",
            location: "Arlington, KS, USA",
            remote: "onsite",
            salary: null,
            postedDate: "2026-01-14",
            applicationUrl: "https://careers.coloplast.com/Kerecis/go/Kerecis/9696001",
            featured: false
        },
        {
            id: 21,
            company: "Kerecis",
            companyLogo: null,
            title: "Wound Care Clinical Specialist",
            description: "Provide clinical expertise and support for Kerecis wound care products across multiple US locations.",
            category: "other",
            type: "full-time",
            experienceLevel: "mid",
            location: "USA (Multiple Locations)",
            remote: "remote",
            salary: null,
            postedDate: "2026-01-12",
            applicationUrl: "https://careers.coloplast.com/Kerecis/go/Kerecis/9696001",
            featured: false
        },
        {
            id: 22,
            company: "Kerecis",
            companyLogo: null,
            title: "Operations Support Associate",
            description: "Support daily operations at Kerecis manufacturing and distribution facility.",
            category: "operations",
            type: "full-time",
            experienceLevel: "entry",
            location: "Arlington, KS, USA",
            remote: "onsite",
            salary: null,
            postedDate: "2026-01-12",
            applicationUrl: "https://careers.coloplast.com/Kerecis/go/Kerecis/9696001",
            featured: false
        },
        {
            id: 23,
            company: "Kerecis",
            companyLogo: null,
            title: "Regenerative Surgical Specialist – Detroit",
            description: "Drive sales of Kerecis fish-skin regenerative tissue products to surgical customers in the Detroit, Michigan region.",
            category: "sales",
            type: "full-time",
            experienceLevel: "mid",
            location: "Detroit, MI, USA",
            remote: "onsite",
            salary: null,
            postedDate: "2026-01-06",
            applicationUrl: "https://careers.coloplast.com/Kerecis/go/Kerecis/9696001",
            featured: false
        },
        {
            id: 24,
            company: "Kerecis",
            companyLogo: null,
            title: "Regenerative Surgical Specialist – Kansas City",
            description: "Drive sales of Kerecis fish-skin regenerative tissue products to surgical customers in the Kansas City region.",
            category: "sales",
            type: "full-time",
            experienceLevel: "mid",
            location: "Kansas City, KS, USA",
            remote: "onsite",
            salary: null,
            postedDate: "2025-12-23",
            applicationUrl: "https://careers.coloplast.com/Kerecis/go/Kerecis/9696001",
            featured: false
        },
        {
            id: 25,
            company: "Kerecis",
            companyLogo: null,
            title: "O.R. Sales Associate – Springfield",
            description: "Support operating room sales activities for Kerecis regenerative tissue products in Springfield, Illinois.",
            category: "sales",
            type: "full-time",
            experienceLevel: "entry",
            location: "Springfield, IL, USA",
            remote: "onsite",
            salary: null,
            postedDate: "2025-12-23",
            applicationUrl: "https://careers.coloplast.com/Kerecis/go/Kerecis/9696001",
            featured: false
        },
        {
            id: 26,
            company: "Kerecis",
            companyLogo: null,
            title: "Conferences Coordinator – Medical Affairs",
            description: "Coordinate medical conferences and events for Kerecis medical affairs team.",
            category: "marketing",
            type: "full-time",
            experienceLevel: "mid",
            location: "Arlington, KS, USA",
            remote: "onsite",
            salary: null,
            postedDate: "2025-12-19",
            applicationUrl: "https://careers.coloplast.com/Kerecis/go/Kerecis/9696001",
            featured: false
        },
        {
            id: 27,
            company: "Kerecis",
            companyLogo: null,
            title: "Patient Access Administrator",
            description: "Manage patient access programs and support for Kerecis regenerative tissue products.",
            category: "operations",
            type: "full-time",
            experienceLevel: "mid",
            location: "Minneapolis, MN, USA",
            remote: "onsite",
            salary: null,
            postedDate: "2025-12-04",
            applicationUrl: "https://careers.coloplast.com/Kerecis/go/Kerecis/9696001",
            featured: false
        },
        {
            id: 28,
            company: "Kerecis",
            companyLogo: null,
            title: "Wound Sales Associate – Indianapolis",
            description: "Drive wound care product sales for Kerecis in the Indianapolis, Indiana region.",
            category: "sales",
            type: "full-time",
            experienceLevel: "entry",
            location: "Indianapolis, IN, USA",
            remote: "onsite",
            salary: null,
            postedDate: "2025-12-03",
            applicationUrl: "https://careers.coloplast.com/Kerecis/go/Kerecis/9696001",
            featured: false
        },
        {
            id: 29,
            company: "Kerecis",
            companyLogo: null,
            title: "Associate Campaign Manager",
            description: "Manage marketing campaigns and digital initiatives for Kerecis products.",
            category: "marketing",
            type: "full-time",
            experienceLevel: "mid",
            location: "Minneapolis, MN, USA",
            remote: "onsite",
            salary: null,
            postedDate: "2025-12-03",
            applicationUrl: "https://careers.coloplast.com/Kerecis/go/Kerecis/9696001",
            featured: false
        },
        {
            id: 30,
            company: "Kerecis",
            companyLogo: null,
            title: "Regenerative Therapy Specialist – Orange County",
            description: "Drive sales of Kerecis fish-skin regenerative tissue products to customers in Orange County, California.",
            category: "sales",
            type: "full-time",
            experienceLevel: "mid",
            location: "Orange County, CA, USA",
            remote: "onsite",
            salary: null,
            postedDate: "2025-12-03",
            applicationUrl: "https://careers.coloplast.com/Kerecis/go/Kerecis/9696001",
            featured: false
        },
        {
            id: 31,
            company: "Kerecis",
            companyLogo: null,
            title: "Wound Sales Associate – Chicago",
            description: "Drive wound care product sales for Kerecis in the Chicago, Illinois region.",
            category: "sales",
            type: "full-time",
            experienceLevel: "entry",
            location: "Chicago, IL, USA",
            remote: "onsite",
            salary: null,
            postedDate: "2025-12-03",
            applicationUrl: "https://careers.coloplast.com/Kerecis/go/Kerecis/9696001",
            featured: false
        },
        {
            id: 32,
            company: "LS Retail",
            companyLogo: null,
            title: "Technical Consultant",
            description: "Provide technical consulting services for LS Retail's unified commerce solutions for retail and hospitality businesses.",
            category: "engineering",
            type: "full-time",
            experienceLevel: "mid",
            location: "Iceland / Porto, Portugal",
            remote: "hybrid",
            salary: null,
            postedDate: "2026-01-20",
            applicationUrl: "https://careers.lsretail.com/jobs",
            featured: false
        },
        {
            id: 33,
            company: "LS Retail",
            companyLogo: null,
            title: "Consultant (German Speaking)",
            description: "Provide consulting services for LS Retail's unified commerce solutions. German language skills required.",
            category: "other",
            type: "full-time",
            experienceLevel: "mid",
            location: "Europe (Remote)",
            remote: "hybrid",
            salary: null,
            postedDate: "2026-01-20",
            applicationUrl: "https://careers.lsretail.com/jobs",
            featured: false
        },
        {
            id: 34,
            company: "LS Retail",
            companyLogo: null,
            title: "Consultant (French Speaking)",
            description: "Provide consulting services for LS Retail's unified commerce solutions. French language skills required.",
            category: "other",
            type: "full-time",
            experienceLevel: "mid",
            location: "Europe (Remote)",
            remote: "hybrid",
            salary: null,
            postedDate: "2026-01-20",
            applicationUrl: "https://careers.lsretail.com/jobs",
            featured: false
        },
        {
            id: 35,
            company: "LS Retail",
            companyLogo: null,
            title: "Technical Consultant MEA",
            description: "Provide technical consulting services for LS Retail's unified commerce solutions in the Middle East and Africa region.",
            category: "engineering",
            type: "full-time",
            experienceLevel: "mid",
            location: "Dubai, UAE",
            remote: "hybrid",
            salary: null,
            postedDate: "2026-01-20",
            applicationUrl: "https://careers.lsretail.com/jobs",
            featured: false
        },
        {
            id: 36,
            company: "Marel",
            companyLogo: null,
            title: "Senior Manager Product Management",
            description: "Lead product portfolio strategy and innovation for the Secondary Fresh business unit. Manage Product Management team, own product roadmap, and drive organizational collaboration across regions.",
            category: "product",
            type: "full-time",
            experienceLevel: "lead",
            location: "Gardabaer, Iceland",
            remote: "onsite",
            salary: null,
            postedDate: "2026-01-14",
            applicationUrl: "https://jbtm.wd108.myworkdayjobs.com/en-US/JBT_Marel_Career_Site/details/Senior-Manager-Product-Management_19979",
            featured: false
        },
        {
            id: 37,
            company: "Meniga",
            companyLogo: null,
            title: "FullStack Developer (.NET)",
            description: "Design, develop, and maintain web applications using .NET in a dynamic fintech environment. Work with .NET Core, Azure, Kubernetes, SQL, TypeScript, and RESTful APIs.",
            category: "engineering",
            type: "full-time",
            experienceLevel: "mid",
            location: "Kópavogur, Iceland",
            remote: "hybrid",
            salary: null,
            postedDate: "2026-01-20",
            applicationUrl: "https://meniga.bamboohr.com/careers/98",
            featured: false
        },
        {
            id: 38,
            company: "Össur",
            companyLogo: null,
            title: "Enterprise Data Architect",
            description: "Lead enterprise data architecture for Össur, a global leader in prosthetics and orthopedic solutions. Design and implement data strategies across the organization.",
            category: "engineering",
            type: "full-time",
            experienceLevel: "senior",
            location: "Reykjavik, Iceland",
            remote: "onsite",
            salary: null,
            postedDate: "2026-01-20",
            applicationUrl: "https://ossur.wd3.myworkdayjobs.com/OssurCareersGlobal",
            featured: false
        },
        {
            id: 39,
            company: "Össur",
            companyLogo: null,
            title: "Manufacturing Engineer",
            description: "Support manufacturing processes for Össur's prosthetic and orthopedic products. Optimize production systems and improve manufacturing efficiency.",
            category: "engineering",
            type: "full-time",
            experienceLevel: "mid",
            location: "Reykjavik, Iceland",
            remote: "onsite",
            salary: null,
            postedDate: "2026-01-16",
            applicationUrl: "https://ossur.wd3.myworkdayjobs.com/OssurCareersGlobal",
            featured: false
        },
        {
            id: 40,
            company: "Össur",
            companyLogo: null,
            title: "Software Developer - Bionics",
            description: "Develop software for Össur's bionic prosthetic products. Work on cutting-edge technology that helps people regain mobility.",
            category: "engineering",
            type: "full-time",
            experienceLevel: "mid",
            location: "Reykjavik, Iceland",
            remote: "onsite",
            salary: null,
            postedDate: "2026-01-09",
            applicationUrl: "https://ossur.wd3.myworkdayjobs.com/OssurCareersGlobal",
            featured: false
        },
        {
            id: 41,
            company: "Embla Medical",
            companyLogo: null,
            title: "Business Central Technical Architect",
            description: "Lead technical architecture for Microsoft Business Central implementations at Embla Medical, the parent company of Össur.",
            category: "engineering",
            type: "full-time",
            experienceLevel: "senior",
            location: "Reykjavik / Remote (UK, Poland, Netherlands)",
            remote: "hybrid",
            salary: null,
            postedDate: "2026-01-09",
            applicationUrl: "https://ossur.wd3.myworkdayjobs.com/OssurCareersGlobal",
            featured: false
        },
        {
            id: 42,
            company: "Embla Medical",
            companyLogo: null,
            title: "Global Category Manager Direct Materials",
            description: "Manage global procurement strategy for direct materials at Embla Medical. Oversee supplier relationships and optimize sourcing across the organization.",
            category: "operations",
            type: "full-time",
            experienceLevel: "senior",
            location: "Reykjavik / Eindhoven",
            remote: "onsite",
            salary: null,
            postedDate: "2026-01-09",
            applicationUrl: "https://ossur.wd3.myworkdayjobs.com/OssurCareersGlobal",
            featured: false
        },
        {
            id: 43,
            company: "Össur",
            companyLogo: null,
            title: "Summer Job 2026 (Sumarstörf)",
            description: "Summer employment opportunity at Össur for 2026. Gain hands-on experience at a global leader in prosthetics and orthopedic solutions.",
            category: "other",
            type: "internship",
            experienceLevel: "entry",
            location: "Reykjavik, Iceland",
            remote: "onsite",
            salary: null,
            postedDate: "2026-01-06",
            applicationUrl: "https://ossur.wd3.myworkdayjobs.com/OssurCareersGlobal",
            featured: false
        },
        {
            id: 44,
            company: "Össur",
            companyLogo: null,
            title: "Design Transfer Engineer",
            description: "Manage the transfer of product designs from R&D to manufacturing. Ensure smooth transition and scalability of new prosthetic and orthopedic products.",
            category: "engineering",
            type: "full-time",
            experienceLevel: "mid",
            location: "Reykjavik, Iceland",
            remote: "onsite",
            salary: null,
            postedDate: "2026-01-06",
            applicationUrl: "https://ossur.wd3.myworkdayjobs.com/OssurCareersGlobal",
            featured: false
        },
        {
            id: 45,
            company: "Össur",
            companyLogo: null,
            title: "Direct Tax Specialist",
            description: "Handle direct tax compliance and planning for Össur's global operations. Work on corporate tax matters across multiple jurisdictions.",
            category: "finance",
            type: "full-time",
            experienceLevel: "mid",
            location: "Reykjavik / Eindhoven",
            remote: "onsite",
            salary: null,
            postedDate: "2025-12-20",
            applicationUrl: "https://ossur.wd3.myworkdayjobs.com/OssurCareersGlobal",
            featured: false
        },
        {
            id: 46,
            company: "Össur",
            companyLogo: null,
            title: "General Application - Production",
            description: "Open application for production roles at Össur. Join the manufacturing team producing world-leading prosthetic and orthopedic products.",
            category: "operations",
            type: "full-time",
            experienceLevel: "entry",
            location: "Reykjavik, Iceland",
            remote: "onsite",
            salary: null,
            postedDate: "2025-12-20",
            applicationUrl: "https://ossur.wd3.myworkdayjobs.com/OssurCareersGlobal",
            featured: false
        },
        {
            id: 47,
            company: "Össur",
            companyLogo: null,
            title: "General Application - Specialists",
            description: "Open application for specialist roles at Össur. Various opportunities across engineering, finance, marketing, and other professional functions.",
            category: "other",
            type: "full-time",
            experienceLevel: "mid",
            location: "Reykjavik, Iceland",
            remote: "onsite",
            salary: null,
            postedDate: "2025-12-20",
            applicationUrl: "https://ossur.wd3.myworkdayjobs.com/OssurCareersGlobal",
            featured: false
        },
        {
            id: 48,
            company: "beqom (PayAnalytics)",
            companyLogo: null,
            title: "Head of Sales, North America",
            description: "Lead sales operations and strategy for beqom's compensation management solutions across North America.",
            category: "sales",
            type: "full-time",
            experienceLevel: "executive",
            location: "New York, USA",
            remote: "hybrid",
            salary: null,
            postedDate: "2026-01-21",
            applicationUrl: "https://beqom.bamboohr.com/careers",
            featured: false
        },
        {
            id: 49,
            company: "beqom (PayAnalytics)",
            companyLogo: null,
            title: "Security Engineer",
            description: "Protect beqom's infrastructure and applications. Work on security architecture, threat detection, and compliance for compensation management solutions.",
            category: "engineering",
            type: "full-time",
            experienceLevel: "mid",
            location: "London / Lisbon / Krakow",
            remote: "hybrid",
            salary: null,
            postedDate: "2026-01-21",
            applicationUrl: "https://beqom.bamboohr.com/careers",
            featured: false
        },
        {
            id: 50,
            company: "beqom (PayAnalytics)",
            companyLogo: null,
            title: "EMEA Account Manager (German Speaking)",
            description: "Manage client relationships and drive growth across EMEA markets. German language skills required.",
            category: "sales",
            type: "full-time",
            experienceLevel: "mid",
            location: "Berlin / Munich / Frankfurt / Nyon",
            remote: "remote",
            salary: null,
            postedDate: "2026-01-21",
            applicationUrl: "https://beqom.bamboohr.com/careers",
            featured: false
        },
        {
            id: 51,
            company: "beqom (PayAnalytics)",
            companyLogo: null,
            title: "Business Development Representative (BDR)",
            description: "Generate new business opportunities and qualify leads for beqom's compensation and pay equity solutions.",
            category: "sales",
            type: "full-time",
            experienceLevel: "entry",
            location: "London, UK",
            remote: "remote",
            salary: null,
            postedDate: "2026-01-21",
            applicationUrl: "https://beqom.bamboohr.com/careers",
            featured: false
        },
        {
            id: 52,
            company: "beqom (PayAnalytics)",
            companyLogo: null,
            title: "Application Support Specialist (L2)",
            description: "Provide Level 2 technical support for beqom's managed services clients. Troubleshoot and resolve application issues.",
            category: "operations",
            type: "full-time",
            experienceLevel: "mid",
            location: "Tivoli / Krakow",
            remote: "hybrid",
            salary: null,
            postedDate: "2026-01-21",
            applicationUrl: "https://beqom.bamboohr.com/careers",
            featured: false
        },
        {
            id: 53,
            company: "beqom (PayAnalytics)",
            companyLogo: null,
            title: "Pay Equity Consultant",
            description: "Advise clients on pay equity analysis and compliance. Help organizations achieve fair and transparent compensation practices.",
            category: "other",
            type: "full-time",
            experienceLevel: "mid",
            location: "Tivoli, Italy",
            remote: "hybrid",
            salary: null,
            postedDate: "2026-01-21",
            applicationUrl: "https://beqom.bamboohr.com/careers",
            featured: false
        },
        {
            id: 54,
            company: "beqom (PayAnalytics)",
            companyLogo: null,
            title: "UX / UI Designer",
            description: "Design intuitive user experiences for beqom's compensation management platform. Create interfaces that make complex data accessible.",
            category: "design",
            type: "full-time",
            experienceLevel: "mid",
            location: "Dublin / Krakow",
            remote: "hybrid",
            salary: null,
            postedDate: "2026-01-21",
            applicationUrl: "https://beqom.bamboohr.com/careers",
            featured: false
        },
        {
            id: 55,
            company: "beqom (PayAnalytics)",
            companyLogo: null,
            title: "Product Owner - Pay Analytics",
            description: "Own the product roadmap for PayAnalytics, beqom's pay equity solution. Drive product strategy and work with engineering teams.",
            category: "product",
            type: "full-time",
            experienceLevel: "mid",
            location: "Dublin / Reykjavik / Krakow",
            remote: "hybrid",
            salary: null,
            postedDate: "2026-01-21",
            applicationUrl: "https://beqom.bamboohr.com/careers",
            featured: true
        },
        {
            id: 56,
            company: "beqom (PayAnalytics)",
            companyLogo: null,
            title: "Product Owner - Platform",
            description: "Own the product roadmap for beqom's core platform. Drive platform strategy and coordinate with development teams.",
            category: "product",
            type: "full-time",
            experienceLevel: "mid",
            location: "Dublin / Krakow",
            remote: "hybrid",
            salary: null,
            postedDate: "2026-01-21",
            applicationUrl: "https://beqom.bamboohr.com/careers",
            featured: false
        },
        {
            id: 57,
            company: "beqom (PayAnalytics)",
            companyLogo: null,
            title: "Project Manager",
            description: "Manage professional services projects for beqom clients. Ensure successful implementation of compensation management solutions.",
            category: "operations",
            type: "full-time",
            experienceLevel: "mid",
            location: "Leeds, UK",
            remote: "remote",
            salary: null,
            postedDate: "2026-01-21",
            applicationUrl: "https://beqom.bamboohr.com/careers",
            featured: false
        },
        {
            id: 58,
            company: "beqom (PayAnalytics)",
            companyLogo: null,
            title: "Service Desk Engineer (L1)",
            description: "Provide first-line technical support for beqom's clients. Handle support tickets and escalate complex issues.",
            category: "operations",
            type: "full-time",
            experienceLevel: "entry",
            location: "Tivoli, Italy",
            remote: "hybrid",
            salary: null,
            postedDate: "2026-01-21",
            applicationUrl: "https://beqom.bamboohr.com/careers",
            featured: false
        },
        {
            id: 59,
            company: "beqom (PayAnalytics)",
            companyLogo: null,
            title: "Business Consultant",
            description: "Deliver consulting services for beqom's compensation management solutions. Work with clients to optimize their compensation processes.",
            category: "other",
            type: "full-time",
            experienceLevel: "mid",
            location: "Leeds, UK",
            remote: "remote",
            salary: null,
            postedDate: "2026-01-21",
            applicationUrl: "https://beqom.bamboohr.com/careers",
            featured: false
        },
        {
            id: 60,
            company: "Smitten",
            companyLogo: null,
            title: "Social Content Lead Sweden",
            description: "Own Smitten's social media voice across TikTok, Instagram, and emerging platforms. Create content that captures attention, be the face of Smitten on socials, and build a community that's playful, bold, and never boring. Part-time freelance role for 3-6 months.",
            category: "marketing",
            type: "part-time",
            experienceLevel: "mid",
            location: "Stockholm, Sweden",
            remote: "onsite",
            salary: null,
            postedDate: "2026-01-21",
            applicationUrl: "https://jobs.50skills.com/smittendating/en/40119",
            featured: false
        },
        {
            id: 61,
            company: "Aftra",
            companyLogo: null,
            title: "Product Software Developer",
            description: "Shape the user experience of Aftra's cybersecurity SaaS solutions. Build complex frontend applications with modern JavaScript frameworks, translate security data into clean intuitive interfaces, and drive technical decisions. Spinoff from Syndis.",
            category: "engineering",
            type: "full-time",
            experienceLevel: "mid",
            location: "Reykjavik, Iceland",
            remote: "hybrid",
            salary: null,
            postedDate: "2026-01-21",
            applicationUrl: "https://alfred.is/starf/product-software-developer",
            featured: false
        },
        {
            id: 62,
            company: "Alor",
            companyLogo: null,
            title: "Project Manager - Solar & BESS Solutions (Rafvirki)",
            description: "Lead installation and project management of large-scale solar energy systems and battery energy storage solutions (BESS) in Iceland. Work on innovative projects including repurposing EV batteries for energy storage.",
            category: "engineering",
            type: "full-time",
            experienceLevel: "mid",
            location: "Iceland",
            remote: "onsite",
            salary: null,
            postedDate: "2026-01-22",
            applicationUrl: "https://alfred.is/en/starf/rafvirki-med-nyskoepunarhugarfar-oskast",
            featured: false
        },
        {
            id: 63,
            company: "Coripharma",
            companyLogo: null,
            title: "Packaging Mechanic",
            description: "Technical role in pharmaceutical manufacturing operating Uhlmann packaging lines and blister machines. Responsible for machine setup, format changeovers, troubleshooting, and ensuring GMP compliance. 5+ years machinery experience required.",
            category: "operations",
            type: "full-time",
            experienceLevel: "mid",
            location: "Hafnarfjörður, Iceland",
            remote: "onsite",
            salary: null,
            postedDate: "2026-01-22",
            applicationUrl: "https://alfred.is/en/starf/velamadur-i-poekkunardeild-packaging-mechanic",
            featured: false
        },
        {
            id: 64,
            company: "Lagaviti",
            companyLogo: null,
            title: "Full Stack / AI Developer",
            description: "Build cutting-edge AI-powered legal technology solutions. Work with LLM APIs (OpenAI, Google, Anthropic), RAG systems, and data-driven workflows. Strong JavaScript/TypeScript or Python skills required, plus interest in AI development.",
            category: "engineering",
            type: "full-time",
            experienceLevel: "mid",
            location: "Reykjavik, Iceland",
            remote: "hybrid",
            salary: null,
            postedDate: "2026-01-22",
            applicationUrl: "https://alfred.is/en/fyrirtaeki/lagaviti",
            featured: false
        },
        {
            id: 65,
            company: "Lagaviti",
            companyLogo: null,
            title: "System Administrator / DevOps",
            description: "Build and maintain infrastructure for AI-powered legal tech platform. Work with Linux, cloud environments (GCP/Azure), Docker, Kubernetes, and CI/CD pipelines. Experience with Infrastructure as Code and monitoring tools preferred.",
            category: "engineering",
            type: "full-time",
            experienceLevel: "mid",
            location: "Reykjavik, Iceland",
            remote: "hybrid",
            salary: null,
            postedDate: "2026-01-22",
            applicationUrl: "https://alfred.is/en/fyrirtaeki/lagaviti",
            featured: false
        },
        {
            id: 66,
            company: "Kríta",
            companyLogo: null,
            title: "Business Manager",
            description: "Build and develop business relationships for Iceland's leading fintech company offering fast and flexible financing solutions. Sell financing products to businesses, manage client relationships, and help shape the sales team.",
            category: "sales",
            type: "full-time",
            experienceLevel: "mid",
            location: "Reykjavik, Iceland",
            remote: "onsite",
            salary: null,
            postedDate: "2026-01-22",
            applicationUrl: "mailto:hr@krita.is",
            featured: false
        },
        {
            id: 67,
            company: "Rapyd Europe",
            companyLogo: null,
            title: "Business Manager",
            description: "Sell payment solutions to Icelandic companies and provide consulting and service to customers. Analyze customer needs, develop sales opportunities, and work with internal service and development teams.",
            category: "sales",
            type: "full-time",
            experienceLevel: "mid",
            location: "Reykjavik, Iceland",
            remote: "onsite",
            salary: null,
            postedDate: "2026-01-22",
            applicationUrl: "https://www.rapyd.net/company/careers/",
            featured: false
        },
        {
            id: 68,
            company: "Alvotech",
            companyLogo: null,
            title: "Senior Aseptic Processing Technologist",
            description: "Join the Drug Product Manufacturing team working in cleanroom environments (Grade A, B, C). Work with cGMP standards, serve as Subject Matter Expert for audits, and identify process improvements. 3+ years pharmaceutical experience required. Shift work.",
            category: "operations",
            type: "full-time",
            experienceLevel: "senior",
            location: "Reykjavik, Iceland",
            remote: "onsite",
            salary: null,
            postedDate: "2026-01-22",
            applicationUrl: "https://www.alvotech.com/careers",
            featured: false
        },
        {
            id: 69,
            company: "Alvotech",
            companyLogo: null,
            title: "Warehouse Operator",
            description: "Receive, store, and handle materials for biosimilar medicine manufacturing according to cGMP standards. Support inventory management, cycle counts, and regulatory audits. Warehouse and forklift experience preferred. Shift work.",
            category: "operations",
            type: "full-time",
            experienceLevel: "entry",
            location: "Reykjavik, Iceland",
            remote: "onsite",
            salary: null,
            postedDate: "2026-01-22",
            applicationUrl: "https://www.alvotech.com/careers",
            featured: false
        },
        {
            id: 70,
            company: "Pikkoló",
            companyLogo: null,
            title: "Delivery Courier",
            description: "Pick up grocery orders from stores and deliver to Pikkoló's refrigerated self-service stations. Join an innovative company building sustainable smart distribution for online grocery stores. Driving license required, 20+ years old. Sundays and Mondays required.",
            category: "operations",
            type: "part-time",
            experienceLevel: "entry",
            location: "Iceland",
            remote: "onsite",
            salary: null,
            postedDate: "2026-01-22",
            applicationUrl: "https://www.pikkolo.is",
            featured: false
        },
        {
            id: 71,
            company: "Teledyne Gavia",
            companyLogo: null,
            title: "Software Quality Assurance Engineer",
            description: "Conduct software testing for autonomous underwater vehicles (AUVs) including submarine control systems and monitoring interfaces. Develop test processes, implement automated tests, and collaborate with development teams to ensure software quality.",
            category: "engineering",
            type: "full-time",
            experienceLevel: "mid",
            location: "Iceland",
            remote: "onsite",
            salary: null,
            postedDate: "2026-01-22",
            applicationUrl: "mailto:hlynur@hagvangur.is",
            featured: false
        }
    ]
};
